headers <- names(read.csv(file="household_power_consumption.txt",sep=";",nrows=1))
Data_org <- read.csv(file="household_power_consumption.txt",header = TRUE,sep=";",skip=66637,nrows=2880,col.names =headers)
Data_org$Date <- as.Date(Data_org$Date,format="%Y/%m/%d")
with(Data_org,plot(Sub_metering_1,type='l',col="black",axes=FALSE,ann=FALSE))
with(Data_org,lines(Sub_metering_2,type='l',col="red"))
with(Data_org,lines(Sub_metering_3,type='l',col="blue"))
axis(1, at=c(1,1440,2880), lab=c("Thu", "Fri", "Sat"))
axis(2)
box()
title(ylab="Energy sub metering")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.copy(png,'Plot3.png')
dev.off()
